- id: 2.1.1
  name: Client certificate authentication should not be used for users (Manual)
  attributeId: 2.1.1
  component: ""
  audit: ""
- id: 2.2.1
  name: Ensure that a minimal audit policy is created (Manual)
  attributeId: 2.2.1
  component: ""
  audit: ""
- id: 2.2.2
  name: Ensure that the audit policy covers key security concerns (Manual)
  attributeId: 2.2.2
  component: ""
  audit: ""
- id: 3.1.1
  name: Proxy kubeconfig file permissions
  attributeId: 4.1.3
  component: proxy
  audit: /bin/sh -c 'if test -e {{ .proxy_kubeconfig }}; then stat -c %a {{ .proxy_kubeconfig }}; else exit 80; fi'
- id: 3.1.2
  name: Proxy kubeconfig file ownership
  attributeId: 4.1.4
  component: proxy
  audit: /bin/sh -c 'if test -e {{ .proxy_kubeconfig }}; then stat -c %U:%G {{ .proxy_kubeconfig }}; else exit 80; fi'
- id: 3.1.3
  name: Kubelet config file permissions
  attributeId: 4.1.9
  component: kubelet
  audit: /bin/sh -c 'if test -e {{ .kubelet_config }}; then stat -c %a {{ .kubelet_config }}; else exit 80; fi'
- id: 3.1.4
  name: Kubelet config file ownership
  attributeId: 4.1.10
  component: kubelet
  audit: /bin/sh -c 'if test -e {{ .kubelet_config }}; then stat -c %U:%G {{ .kubelet_config }}; else exit 80; fi'
- id: 3.2.1
  name: Kubelet --anonymous-auth
  attributeId: 4.2.1
  component: kubelet
  audit: |
    VAL=$(ps -ef | grep {{ .kubelet_bin }} | grep -- --anonymous-auth | sed 's%.*anonymous-auth[= ]\([^ ]*\).*%\1%')
    if test -z $VAL; then VAL=$(cat {{ .kubelet_config }} | awk '/^[^[:blank:]]/{p=0} /authentication/{p=1} p' | grep -A1 "anonymous:" | grep "enabled": | sed 's%.*[= ]\([^ ]*\).*%\1%'); fi
    echo $VAL
- id: 3.2.2
  name: Kubelet --authorization-mode
  attributeId: 4.2.2
  component: kubelet
  audit: |
    VAL=$(ps -ef | grep {{ .kubelet_bin }} | grep -- --authorization-mode | sed 's%.*authorization-mode[= ]\([^ ]*\).*%\1%')
    if test -z $VAL; then VAL=$(cat {{ .kubelet_config }} | awk '/^[^[:blank:]]/{p=0} /authorization/{p=1} p' | grep "mode:" | sed 's%.*[= ]\([^ ]*\).*%\1%'); fi
    echo $VAL
- id: 3.2.3
  name: Kubelet --client-ca-file
  attributeId: 4.2.3
  component: kubelet
  audit: |
    VAL=$(ps -ef | grep {{ .kubelet_bin }} | grep -- --client-ca-file | sed 's%.*client-ca-file[= ]\([^ ]*\).*%\1%')
    if test -z $VAL; then VAL=$(cat {{ .kubelet_config }} | awk '/^[^[:blank:]]/{p=0} /authentication/{p=1} p' | grep -A1 "x509:" | grep "clientCAFile": | sed 's%.*[= ]\([^ ]*\).*%\1%'); fi
    echo $VAL
- id: 3.2.4
  name: Kubelet --read-only-port
  attributeId: 4.2.4
  component: kubelet
  audit: |
    VAL=$(ps -ef | grep {{ .kubelet_bin }} | grep -- --read-only-port | sed 's%.*read-only-port[= ]\([^ ]*\).*%\1%')
    if test -z $VAL; then VAL=$(cat {{ .kubelet_config }} | grep "readOnlyPort:" | sed 's%.*[= ]\([^ ]*\).*%\1%'); fi
    echo $VAL
- id: 3.2.5
  name: Kubelet --streaming-connection-idle-timeout
  attributeId: 4.2.5
  component: kubelet
  audit: |
    VAL=$(ps -ef | grep {{ .kubelet_bin }} | grep -- --streaming-connection-idle-timeout | sed 's%.*streaming-connection-idle-timeout[= ]\([^ ]*\).*%\1%')
    if test -z $VAL; then VAL=$(cat {{ .kubelet_config }} | grep 'streamingConnectionIdleTimeout:' | sed 's%.*[= ]\([^ ]*\).*%\1%'); fi
    echo $VAL
- id: 3.2.6
  name: Kubelet --protect-kernel-defaults
  attributeId: 4.2.6
  component: kubelet
  audit: |
    VAL=$(ps -ef | grep {{ .kubelet_bin }} | grep -- --protect-kernel-defaults | sed 's%.*protect-kernel-defaults[= ]\([^ ]*\).*%\1%')
    if test -z $VAL; then VAL=$(cat {{ .kubelet_config }} | grep 'protectKernelDefaults:' | sed 's%.*[= ]\([^ ]*\).*%\1%'); fi
    echo $VAL
- id: 3.2.7
  name: Kubelet --make-iptables-util-chains
  attributeId: 4.2.7
  component: kubelet
  audit: |
    VAL=$(ps -ef | grep {{ .kubelet_bin }} | grep -- --make-iptables-util-chains | sed 's%.*make-iptables-util-chains[= ]\([^ ]*\).*%\1%')
    if test -z $VAL; then VAL=$(cat {{ .kubelet_config }} | grep 'makeIPTablesUtilChains:' | sed 's%.*[= ]\([^ ]*\).*%\1%'); fi
    echo $VAL
- id: 3.2.8
  name: Kubelet --hostname-override
  attributeId: 4.2.8
  component: kubelet
  audit: ps -ef | grep {{ .kubelet_bin }} | grep -- --hostname-override | sed 's%.*hostname-override[= ]\([^ ]*\).*%\1%'
- id: 3.2.9
  name: Kubelet --event-qps
  attributeId: 4.2.9
  component: kubelet
  audit: |
    VAL=$(ps -ef | grep {{ .kubelet_bin }} | grep -- --event-qps | sed 's%.*event-qps[= ]\([^ ]*\).*%\1%')
    if test -z $VAL; then VAL=$(cat {{ .kubelet_config }} | grep 'eventRecordQPS:' | sed 's%.*[= ]\([^ ]*\).*%\1%'); fi
    echo $VAL
- id: 3.2.10
  name: Kubelet --tls-cert-file & --tls-private-key-file
  attributeId: 4.2.10
  component: kubelet
  audit: |
    CERT=$(ps -ef | grep {{ .kubelet_bin }} | grep -- --tls-cert-file | sed 's%.*tls-cert-file[= ]\([^ ]*\).*%\1%')
    if test -z $CERT; then CERT=$(cat {{ .kubelet_config }} | grep 'tlsCertFile:' | sed 's%.*[= ]\([^ ]*\).*%\1%'); fi
    if [ "$CERT" == "null" ]; then CERT=''; fi

    KEY=$(ps -ef | grep {{ .kubelet_bin }} | grep -- --tls-private-key-file | sed 's%.*tls-private-key-file[= ]\([^ ]*\).*%\1%')
    if test -z $KEY; then KEY=$(cat {{ .kubelet_config }} | grep 'tlsPrivateKeyFile:' | sed 's%.*[= ]\([^ ]*\).*%\1%'); fi
    if [ "$KEY" == "null" ]; then KEY=''; fi

    echo $CERT
    echo $KEY
- id: 3.2.11
  name: Kubelet --rotate-certificates
  attributeId: 4.2.11
  component: kubelet
  audit: |
    VAL=$(ps -ef | grep {{ .kubelet_bin }} | grep -- --rotate-certificates | sed 's%.*rotate-certificates[= ]\([^ ]*\).*%\1%')
    if test -z $VAL; then VAL=$(cat {{ .kubelet_config }} | grep 'rotateCertificates:' | sed 's%.*[= ]\([^ ]*\).*%\1%'); fi
    echo $VAL
- id: 3.2.12
  name: Kubelet RotateKubeletServerCertificate
  attributeId: 4.2.12
  component: kubelet
  audit: |
    VAL=$(ps -ef | grep {{ .kubelet_bin }} | grep -- RotateKubeletServerCertificate | sed 's%.*RotateKubeletServerCertificate[= ]\([^ ]*\).*%\1%')
    if test -z $VAL; then VAL=$(cat {{ .kubelet_config }} | grep featureGates | grep RotateKubeletServerCertificate= | sed 's%.*RotateKubeletServerCertificate[= ]\([^ ]*\).*%\1%' | sed 's/,.*//'); fi
    echo $VAL
- id: 4.1.1
  name: Ensure that the cluster-admin role is only used where required (Manual)
  attributeId: 4.1.1-gke
  component: ""
  audit: ""
- id: 4.1.2
  name: Minimize access to secrets (Manual)
  attributeId: 4.1.2-gke
  component: ""
  audit: ""
- id: 4.1.3
  name: Minimize wildcard use in Roles and ClusterRoles (Manual)
  attributeId: 4.1.3-gke
  component: ""
  audit: ""
- id: 4.1.4
  name: Minimize access to create pods (Manual)
  attributeId: 4.1.4-gke
  component: ""
  audit: ""
- id: 4.1.5
  name: Ensure that default service accounts are not actively used. (Manual)
  attributeId: 4.1.5-gke
  component: ""
  audit: ""
- id: 4.1.6
  name: Ensure that Service Account Tokens are only mounted where necessary (Manual)
  attributeId: 4.1.6-gke
  component: ""
  audit: ""
- id: 4.2.1
  name: Minimize the admission of privileged containers (Automated)
  attributeId: 4.2.1-gke
  component: ""
  audit: ""
- id: 4.2.2
  name: Minimize the admission of containers wishing to share the host process ID namespace (Automated)
  attributeId: 4.2.2-gke
  component: ""
  audit: ""
- id: 4.2.3
  name: Minimize the admission of containers wishing to share the host IPC namespace (Automated)
  attributeId: 4.2.3-gke
  component: ""
  audit: ""
- id: 4.2.4
  name: Minimize the admission of containers wishing to share the host network namespace (Automated)
  attributeId: 4.2.4-gke
  component: ""
  audit: ""
- id: 4.2.5
  name: Minimize the admission of containers with allowPrivilegeEscalation (Automated)
  attributeId: 4.2.5-gke
  component: ""
  audit: ""
- id: 4.2.6
  name: Minimize the admission of root containers (Automated)
  attributeId: 4.2.6-gke
  component: ""
  audit: ""
- id: 4.2.7
  name: Minimize the admission of containers with the NET_RAW capability (Automated)
  attributeId: 4.2.7-gke
  component: ""
  audit: ""
- id: 4.2.8
  name: Minimize the admission of containers with added capabilities (Automated)
  attributeId: 4.2.8-gke
  component: ""
  audit: ""
- id: 4.2.9
  name: Minimize the admission of containers with capabilities assigned (Manual)
  attributeId: 4.2.9-gke
  component: ""
  audit: ""
- id: 4.3.1
  name: Ensure that the CNI in use supports Network Policies (Manual)
  attributeId: 4.3.1-gke
  component: ""
  audit: ""
- id: 4.3.2
  name: Ensure that all Namespaces have Network Policies defined (Manual)
  attributeId: 4.3.2-gke
  component: ""
  audit: ""
- id: 4.4.1
  name: Prefer using secrets as files over secrets as environment variables (Manual)
  attributeId: 4.4.1-gke
  component: ""
  audit: ""
- id: 4.4.2
  name: Consider external secret storage (Manual)
  attributeId: 4.4.2-gke
  component: ""
  audit: ""
- id: 4.5.1
  name: Configure Image Provenance using ImagePolicyWebhook admission controller (Manual)
  attributeId: 4.5.1-gke
  component: ""
  audit: ""
- id: 4.6.1
  name: Create administrative boundaries between resources using namespaces (Manual)
  attributeId: 4.6.1-gke
  component: ""
  audit: ""
- id: 4.6.2
  name: Ensure that the seccomp profile is set to docker/default in your pod definitions (Manual)
  attributeId: 4.6.2-gke
  component: ""
  audit: ""
- id: 4.6.3
  name: Apply Security Context to Your Pods and Containers (Manual)
  attributeId: 4.6.3-gke
  component: ""
  audit: ""
- id: 5.1.1
  name: Ensure Image Vulnerability Scanning using GCR Container Analysis or a third-party provider (Manual)
  attributeId: 5.1.1
  component: ""
  audit: ""
- id: 5.1.2
  name: Minimize user access to GCR (Manual)
  attributeId: 5.1.2
  component: ""
  audit: ""
- id: 5.1.3
  name: Minimize cluster access to read-only for GCR (Manual)
  attributeId: 5.1.3
  component: ""
  audit: ""
- id: 5.1.4
  name: Minimize Container Registries to only those approved (Manual)
  attributeId: 5.1.4
  component: ""
  audit: ""
- id: 5.2.1
  name: Ensure GKE clusters are not running using the Compute Engine default service account (Manual)
  attributeId: 5.2.1
  component: ""
  audit: ""
- id: 5.2.2
  name: Prefer using dedicated GCP Service Accounts and Workload Identity (Manual)
  attributeId: 5.2.2
  component: ""
  audit: ""
- id: 5.3.1
  name: Ensure Kubernetes Secrets are encrypted using keys managed in Cloud KMS (Manual)
  attributeId: 5.3.1
  component: ""
  audit: ""
- id: 5.4.1
  name: Ensure legacy Compute Engine instance metadata APIs are Disabled (Automated)
  attributeId: 5.4.1
  component: ""
  audit: ""
- id: 5.4.2
  name: Ensure the GKE Metadata Server is Enabled (Automated)
  attributeId: 5.4.2
  component: ""
  audit: ""
- id: 5.5.1
  name: Ensure Container-Optimized OS (COS) is used for GKE node images (Automated)
  attributeId: 5.5.1
  component: ""
  audit: ""
- id: 5.5.2
  name: Ensure Node Auto-Repair is enabled for GKE nodes (Automated)
  attributeId: 5.5.2
  component: ""
  audit: ""
- id: 5.5.3
  name: Ensure Node Auto-Upgrade is enabled for GKE nodes (Automated)
  attributeId: 5.5.3
  component: ""
  audit: ""
- id: 5.5.4
  name: Automate GKE version management using Release Channels (Manual)
  attributeId: 5.5.4
  component: ""
  audit: ""
- id: 5.5.5
  name: Ensure Shielded GKE Nodes are Enabled (Manual)
  attributeId: 5.5.5
  component: ""
  audit: ""
- id: 5.5.6
  name: Ensure Integrity Monitoring for Shielded GKE Nodes is Enabled (Automated)
  attributeId: 5.5.6
  component: ""
  audit: ""
- id: 5.5.7
  name: Ensure Secure Boot for Shielded GKE Nodes is Enabled (Automated)
  attributeId: 5.5.7
  component: ""
  audit: ""
- id: 5.6.1
  name: Enable VPC Flow Logs and Intranode Visibility (Automated)
  attributeId: 5.6.1
  component: ""
  audit: ""
- id: 5.6.2
  name: Ensure use of VPC-native clusters (Automated)
  attributeId: 5.6.2
  component: ""
  audit: ""
- id: 5.6.3
  name: Ensure Master Authorized Networks is Enabled (Manual)
  attributeId: 5.6.3
  component: ""
  audit: ""
- id: 5.6.4
  name: Ensure clusters are created with Private Endpoint Enabled and Public Access Disabled (Manual)
  attributeId: 5.6.4
  component: ""
  audit: ""
- id: 5.6.5
  name: Ensure clusters are created with Private Nodes (Manual)
  attributeId: 5.6.5
  component: ""
  audit: ""
- id: 5.6.6
  name: Consider firewalling GKE worker nodes (Manual)
  attributeId: 5.6.6
  component: ""
  audit: ""
- id: 5.6.7
  name: Ensure Network Policy is Enabled and set as appropriate (Manual)
  attributeId: 5.6.7
  component: ""
  audit: ""
- id: 5.6.8
  name: Ensure use of Google-managed SSL Certificates (Manual)
  attributeId: 5.6.8
  component: ""
  audit: ""
- id: 5.7.1
  name: Ensure Stackdriver Kubernetes Logging and Monitoring is Enabled (Automated)
  attributeId: 5.7.1
  component: ""
  audit: ""
- id: 5.7.2
  name: Enable Linux auditd logging (Manual)
  attributeId: 5.7.2
  component: ""
  audit: ""
- id: 5.8.1
  name: Ensure Basic Authentication using static passwords is Disabled (Automated)
  attributeId: 5.8.1
  component: ""
  audit: ""
- id: 5.8.2
  name: Ensure authentication using Client Certificates is Disabled (Automated)
  attributeId: 5.8.2
  component: ""
  audit: ""
- id: 5.8.3
  name: Manage Kubernetes RBAC users with Google Groups for GKE (Manual)
  attributeId: 5.8.3
  component: ""
  audit: ""
- id: 5.8.4
  name: Ensure Legacy Authorization (ABAC) is Disabled (Automated)
  attributeId: 5.8.4
  component: ""
  audit: ""
- id: 5.9.1
  name: Enable Customer-Managed Encryption Keys (CMEK) for GKE Persistent Disks (PD) (Manual)
  attributeId: 5.9.1
  component: ""
  audit: ""
- id: 5.10.1
  name: Ensure Kubernetes Web UI is Disabled (Automated)
  attributeId: 5.10.1
  component: ""
  audit: ""
- id: 5.10.2
  name: Ensure that Alpha clusters are not used for production workloads (Automated)
  attributeId: 5.10.2
  component: ""
  audit: ""
- id: 5.10.3
  name: Ensure Pod Security Policy is Enabled and set as appropriate (Manual)
  attributeId: 5.10.3
  component: ""
  audit: ""
- id: 5.10.4
  name: Consider GKE Sandbox for running untrusted workloads (Manual)
  attributeId: 5.10.4
  component: ""
  audit: ""
- id: 5.10.5
  name: Ensure use of Binary Authorization (Automated)
  attributeId: 5.10.5
  component: ""
  audit: ""
- id: 5.10.6
  name: Enable Cloud Security Command Center (Cloud SCC) (Manual)
  attributeId: 5.10.6
  component: ""
  audit: ""
