- id: "1.1"
  name: Maintain default behavior for anonymous access

- id: "1.2"
  name: Verify that the basic-auth-file method is not enabled
  audit: "yq '.kubernetesMasterConfig.apiServerArguments.basic-auth-file' /etc/origin/master/master-config.yaml"

- id: "1.3"
  name: Insecure Tokens

- id: "1.4"
  name: Secure communications between the API server and master nodes
  audit: |
    ca=$(yq '.kubeletClientInfo.ca' /etc/origin/master/master-config.yaml)
    certFile=$(yq '.kubeletClientInfo.certFile' /etc/origin/master/master-config.yaml)
    keyFile=$(yq '.kubeletClientInfo.keyFile' /etc/origin/master/master-config.yaml)
    port=$(yq '.kubeletClientInfo.port' /etc/origin/master/master-config.yaml)
    echo "{\"ca\": ${ca:=\"\"}, \"certFile\": ${certFile:=\"\"}, \"keyFile\": ${keyFile:=\"\"}, \"port\": ${port:=\"\"}}"

- id: "1.5"
  name: Prevent insecure bindings
  audit: "yq '.kubernetesMasterConfig.insecure-bind-address' /etc/origin/master/master-config.yaml"

- id: "1.6"
  name: Prevent insecure port access
  audit: "yq '.kubernetesMasterConfig.apiServerArguments.insecure-port' /etc/origin/master/master-config.yaml"

- id: "1.7"
  name: Use Secure Ports for API Server Traffic
  audit: "yq '.kubernetesMasterConfig.apiServerArguments.secure-port' /etc/origin/master/master-config.yaml"

- id: "1.8"
  name: Do not expose API server profiling data

- id: "1.9"
  name: Verify repair-malformed-updates argument for API compatibility
  audit: "yq '.repair-malformed-updates' /etc/origin/master/master-config.yaml"

- id: "1.10"
  name: Verify that the AlwaysAdmit admission controller is disabled
  audit: "yq '.AlwaysAdmit' /etc/origin/master/master-config.yaml"

- id: "1.11"
  name: Manage the AlwaysPullImages admission controller
  audit: "yq '.admissionConfig.pluginConfig.configuration.disable' /etc/origin/master/master-config.yaml"

- id: "1.12"
  name: Use Security Context Constraints instead of DenyEscalatingExec admission

- id: "1.13"
  name: Use Security Context Constraints instead of the SecurityContextDeny admission controller

- id: "1.14"
  name: Manage the NamespaceLifecycle admission controller
  audit: "yq '.NamespaceLifecycle' /etc/origin/master/master-config.yaml"

- id: "1.15"
  name: Configure API server auditing - audit log file path
  audit: "yq '.auditConfig.enabled' /etc/origin/master/master-config.yaml"

- id: "1.16"
  name: Configure API server auditing - audit log retention
  audit: "yq '.auditConfig.maximumFileRetentionDays' /etc/origin/master/master-config.yaml"

- id: "1.17"
  name: Configure API server auditing - audit log backup retention
  audit: "yq '.auditConfig.maximumRetainedFiles' /etc/origin/master/master-config.yaml"

- id: "1.18"
  name: Configure audit log file size
  audit: "yq '.auditConfig.maximumFileSizeMegabytes' /etc/origin/master/master-config.yaml"

- id: "1.19"
  name: Verify that authorization-mode is not set to AlwaysAllow
  audit: "yq '.kubernetesMasterConfig.apiServerArguments.authorization-mode' /etc/origin/master/master-config.yaml"

- id: "1.20"
  name: Verify that the token-auth-file flag is not set
  audit: "yq '.kubernetesMasterConfig.apiServerArguments.token-auth-file' /etc/origin/master/master-config.yaml"

#TODO: check - certificat?
- id: "1.21"
  name: Verify the API server certificate authority
  audit: "yq '.kubernetesMasterConfig.apiServerArguments.kubelet-certificat-authority' /etc/origin/master/master-config.yaml"

- id: "1.22"
  name: Verify the API server client certificate and client key
  audit: |
    yq '.kubeletClientInfo.certFile' /etc/origin/master/master-config.yaml
    yq '.kubeletClientInfo.keyFile' /etc/origin/master/master-config.yaml

- id: "1.23"
  name: Verify that the service account lookup flag is not set

- id: "1.24"
  name: Verify the PodSecurityPolicy is disabled to ensure use of SecurityContextConstraints

- id: "1.25"
  name: Verify that the service account key file argument is not set
  audit: |
    yq '.serviceAccountConfig.privateKeyFile' /etc/origin/master/master-config.yaml
    yq '.serviceAccountConfig.publicKeyFiles' /etc/origin/master/master-config.yaml

- id: "1.26"
  name: Verify the certificate and key used for communication with etcd
  audit: |
    yq '.etcdClientInfo.certFile' /etc/origin/master/master-config.yaml
    yq '.etcdClientInfo.keyFile' /etc/origin/master/master-config.yaml

- id: "1.27"
  name: Verify that the ServiceAccount admission controller is enabled
  audit: yq '.ServiceAccount.configuration.disable' /etc/origin/master/master-config.yaml

- id: "1.28"
  name: Verify the certificate and key used to encrypt API server traffic
  audit: |
    yq '.servingInfo.certFile' /etc/origin/master/master-config.yaml
    yq '.servingInfo.keyFile' /etc/origin/master/master-config.yaml

- id: "1.29"
  name: Verify that the --client-ca-file argument is not set
  audit: yq '.servingInfo.clientCA' /etc/origin/master/master-config.yaml

- id: "1.30"
  name: Verify the CA used for communication with etcd
  audit: yq '.etcdClientInfo.ca' /etc/origin/master/master-config.yaml

- id: "1.31"
  name: Verify that the authorization-mode argument is not set

- id: "1.32"
  name: Verify that the NodeRestriction admission controller is enabled
  audit: yq '.NodeRestriction.configuration.disable' /etc/origin/master/master-config.yaml

- id: "1.33"
  name: Configure encryption of data at rest in etcd datastore
  audit: yq '.kubernetesMasterConfig.apiServerArguments.experimental-encryption-provider-config' /etc/origin/master/master-config.yaml

# CHECK
- id: "1.34"
  name: Set the encryption provider to aescbc for etcd data at rest
  audit: yq '.kubernetesMasterConfig.apiServerArguments.experimental-encryption-provider-config.resources[*].providers[*].aescbc.keys[*]' /etc/origin/master/master-config.yaml

- id: "1.35"
  name: Enable the EventRateLimit plugin
  audit: yq '.admissionConfig.pluginConfig.AlwaysPullImages.configuration.disable' /etc/origin/master/master-config.yaml

- id: "1.36"
  name: Configure advanced auditing
  audit: yq '.kubernetesMasterConfig.apiServerArguments.feature-gates.AdvancedAuditing' /etc/origin/master/master-config.yaml

# CHECK
- id: "1.37"
  name: Adjust the request timeout argument for your cluster resources
  audit: grep request-timeout /etc/origin/master/master-config.yaml

- id: "2.1"
  name: Verify that Scheduler profiling is not exposed to the web

- id: "3.1"
  name: Adjust the terminated-pod-gc-threshold argument as needed
  audit: yq '.kubernetesMasterConfig.controllerArguments.terminated-pod-gc-threshold' /etc/origin/master/master-config.yaml

- id: "3.2"
  name: Verify that Controller profiling is not exposed to the web

- id: "3.3"
  name: Verify that the --use-service-account-credentials argument is set to true
  audit: yq '.kubernetesMasterConfig.controllerArguments.use-service-account-credentials' /etc/origin/master/master-config.yaml

- id: "3.4"
  name: Verify that the --service-account-private-key-file argument is set as appropriate
  audit: |
    grep -A9 serviceAccountConfig /etc/origin/master/master-config.yaml | grep privateKeyFile
    grep -A2 service-account-private-key-file /etc/origin/master/master-config.yaml

- id: "3.5"
  name: Verify that the --root-ca-file argument is set as appropriate
  audit: |
    yq '.serviceAccountConfig.root-ca-file' /etc/origin/master/master-config.yaml
    yq '.serviceAccountConfig.masterCA' /etc/origin/master/master-config.yaml

- id: "3.6"
  name: Verify that Security Context Constraints are applied to Your Pods and Containers

- id: "3.7"
  name: Manage certificate rotation
  audit: yq '.kubeletArguments.feature-gates.RotateKubeletServerCertificate' /etc/origin/master/master-config.yaml

- id: "4.1"
  name: Verify the OpenShift default permissions for the API server pod specification file
  audit: stat -c %a /etc/origin/node/pods/apiserver.yaml

- id: "4.2"
  name: Verify the OpenShift default file ownership for the API server pod specification file
  audit: stat -c %U:%G /etc/origin/node/pods/apiserver.yaml

- id: "4.3"
  name: Verify the OpenShift default file permissions for the controller manager pod specification file
  audit: stat -c %a /etc/origin/node/pods/controller.yaml

- id: "4.4"
  name: Verify the OpenShift default ownership for the controller manager pod specification file
  audit: stat -c %U:%G /etc/origin/node/pods/controller.yaml

- id: "4.5"
  name: Verify the OpenShift default permissions for the scheduler pod specification file
  audit: stat -c %a /etc/origin/node/pods/controller.yaml

- id: "4.6"
  name: Verify the scheduler pod specification file ownership set by OpenShift
  audit: stat -c %U:%G /etc/origin/node/pods/controller.yaml

- id: "4.7"
  name: Verify the OpenShift default etcd pod specification file permissions
  audit: stat -c %a /etc/origin/node/pods/etcd.yaml

- id: "4.8"
  name: Verify the OpenShift default etcd pod specification file ownership
  audit: stat -c %U:%G /etc/origin/node/pods/etcd.yaml

- id: "4.9"
  name: Verify the default OpenShift Container Network Interface file permissions
  audit: stat -c %a /etc/origin/openvswitch/ /etc/cni/net.d/

- id: "4.10"
  name: Verify the default OpenShift Container Network Interface file ownership
  audit: stat -c %U:%G /etc/origin/openvswitch/ /etc/cni/net.d/

- id: "4.11"
  name: Verify the default OpenShift etcd data directory permissions
  audit: stat -c %a /var/lib/etcd

- id: "4.12"
  name: Verify the default OpenShift etcd data directory ownership
  audit: stat -c %U:%G /var/lib/etcd

- id: "4.13"
  name: Verify the default OpenShift admin.conf file permissions
  audit: stat -c %a /etc/origin/master/admin.kubeconfig

- id: "4.14"
  name: Verify the default OpenShift admin.conf file ownership
  audit: stat -c %U:%G /etc/origin/master/admin.kubeconfig

- id: "4.15"
  name: Verify the default OpenShift scheduler.conf file permissions
  audit: stat -c %a /etc/origin/master/openshift-master.kubeconfig

- id: "4.16"
  name: Verify the default OpenShift scheduler.conf file ownership
  audit: stat -c %U:%G /etc/origin/master/openshift-master.kubeconfig

- id: "4.17"
  name: Verify the default Openshift controller-manager.conf file permissions
  audit: stat -c %a /etc/origin/master/openshift-master.kubeconfig

- id: "4.18"
  name: Ensure that the controller-manager.conf file ownership is set to root:root (Scored)
  audit: stat -c %U:%G /etc/origin/master/openshift-master.kubeconfig

- id: "5.1"
  name: Verify the default OpenShift cert-file and key-file configuration
  audit: /bin/sh -c '/usr/local/bin/master-exec etcd etcd grep ETCD_CERT_FILE=/etc/etcd/server.crt /proc/1/environ; /usr/local/bin/master-exec etcd etcd grep ETCD_KEY_FILE=/etc/etcd/server.key /proc/1/environ; grep ETCD_CERT_FILE=/etc/etcd/server.crt /etc/etcd/etcd.conf; grep ETCD_KEY_FILE=/etc/etcd/server.key /etc/etcd/etcd.conf'

- id: "5.2"
  name: Verify the default OpenShift setting for the client-cert-auth argument
  audit: /bin/sh -c '/usr/local/bin/master-exec etcd etcd grep ETCD_CLIENT_CERT_AUTH=true /proc/1/environ; grep ETCD_CLIENT_CERT_AUTH /etc/etcd/etcd.conf'

- id: "5.3"
  name: Verify the OpenShift default values for etcd_auto_tls
  audit: /bin/sh -c '/usr/local/bin/master-exec etcd etcd grep ETCD_AUTO_TLS /proc/1/environ; grep ETCD_AUTO_TLS /etc/etcd/etcd.conf'

- id: "5.4"
  name: Verify the OpenShift default peer-cert-file and peer-key-file arguments for etcd
  audit: /bin/sh -c '/usr/local/bin/master-exec etcd etcd grep ETCD_PEER_CERT_FILE=/etc/etcd/peer.crt /proc/1/environ; /usr/local/bin/master-exec etcd etcd grep ETCD_PEER_KEY_FILE=/etc/etcd/peer.key /proc/1/environ; grep ETCD_PEER_CERT_FILE /etc/etcd/etcd.conf; grep ETCD_PEER_KEY_FILE /etc/etcd/etcd.conf'

- id: "5.5"
  name: Verify the OpenShift default configuration for the peer-client-cert-auth
  audit: /bin/sh -c '/usr/local/bin/master-exec etcd etcd grep ETCD_PEER_CLIENT_CERT_AUTH=true /proc/1/environ; grep ETCD_PEER_CLIENT_CERT_AUTH /etc/etcd/etcd.conf'

- id: "5.6"
  name: Verify the OpenShift default configuration for the peer-auto-tls argument
  audit: /bin/sh -c '/usr/local/bin/master-exec etcd etcd grep ETCD_PEER_AUTO_TLS /proc/1/environ; grep ETCD_PEER_AUTO_TLS /etc/etcd/etcd.conf'

- id: "5.7"
  name: Optionally modify the wal-dir argument

- id: "5.8"
  name: Optionally modify the max-wals argument

- id: "5.9"
  name: Verify the OpenShift default configuration for the etcd Certificate Authority
  audit: openssl x509 -in /etc/origin/master/master.etcd-ca.crt -subject -issuer -noout | sed 's/@/ /'

- id: "6.1"
  name: Ensure that the cluster-admin role is only used where required

- id: "6.2"
  name: Verify Security Context Constraints as in use

- id: "6.3"
  name: Use OpenShift projects to maintain boundaries between resources

- id: "6.4"
  name: Create network segmentation using the Multi-tenant plugin or Network Policies

- id: "6.5"
  name: Enable seccomp and configure custom Security Context Constraints

- id: "6.6"
  name: Review Security Context Constraints

- id: "6.7"
  name: Manage Image Provenance using ImagePolicyWebhook admission controller

- id: "6.8"
  name: Configure Network policies as appropriate

- id: "6.9"
  name: Use Security Context Constraints as compensating controls for privileged containers

- id: "7.1"
  name: Use Security Context Constraints to manage privileged containers as needed
  component: "kubelet"

- id: "7.2"
  name: Ensure anonymous-auth is not disabled
  component: "kubelet"

- id: "7.3"
  name: Verify that the --authorization-mode argument is set to WebHook
  component: "kubelet"
  audit: "yq '.kubeletArguments.authorization-mode' /etc/origin/node/node-config.yaml"

- id: "7.4"
  name: Verify the OpenShift default for the client-ca-file argument
  component: "kubelet"
  audit: "yq '.PodManifestConfig.client-ca-file' /etc/origin/node/node-config.yaml"

- id: "7.5"
  name: Verify the OpenShift default setting for the read-only-port argument
  component: "kubelet"
  audit: "yq '.kubeletArguments.read-only-port' /etc/origin/node/node-config.yaml"

- id: "7.6"
  name: Adjust the streaming-connection-idle-timeout argument
  component: "kubelet"
  audit: "yq '.kubeletArguments.streaming-connection-idle-timeout' /etc/origin/node/node-config.yaml"

- id: "7.7"
  name: Verify the OpenShift defaults for the protect-kernel-defaults argument
  component: "kubelet"

- id: "7.8"
  name: Verify the OpenShift default value of true for the make-iptables-util-chains argument
  component: "kubelet"
  audit: "yq '.kubeletArguments.make-iptables-util-chains' /etc/origin/node/node-config.yaml"

- id: "7.9"
  name: Verify that the --keep-terminated-pod-volumes argument is set to false
  component: "kubelet"
  audit: "yq '.kubeletArguments.keep-terminated-pod-volumes' /etc/origin/node/node-config.yaml"

- id: "7.10"
  name: Verify the OpenShift defaults for the hostname-override argument
  component: "kubelet"

- id: "7.11"
  name: Set the --event-qps argument to 0
  component: "kubelet"
  audit: "yq '.kubeletArguments.event-qps' /etc/origin/node/node-config.yaml"

- id: "7.12"
  name: Verify the OpenShift cert-dir flag for HTTPS traffic
  component: "kubelet"
  audit: "yq '.kubeletArguments.cert-dir' /etc/origin/node/node-config.yaml"

- id: "7.13"
  name: Verify the OpenShift default of 0 for the cadvisor-port argument
  component: "kubelet"
  audit: "yq '.kubeletArguments.cadvisor-port' /etc/origin/node/node-config.yaml"

- id: "7.14"
  name: Verify that the RotateKubeletClientCertificate argument is set to true
  component: "kubelet"
  audit: "yq '.kubeletArguments.feature-gates' /etc/origin/node/node-config.yaml"

- id: "7.15"
  name: Verify that the RotateKubeletServerCertificate argument is set to true
  component: "kubelet"
  audit: "yq '.kubeletArguments.feature-gates' /etc/origin/node/node-config.yaml"

- id: "8.1"
  name: Verify the OpenShift default permissions for the kubelet.conf file
  component: "kubelet"
  audit: stat -c %a  /etc/origin/node/node.kubeconfig

- id: "8.2"
  name: Verify the kubeconfig file ownership of root:root
  component: "kubelet"
  audit: stat -c %U:%G /etc/origin/node/node.kubeconfig

- id: "8.3"
  name: Verify the kubelet service file permissions of 644
  component: "kubelet"
  audit: stat -c %a {{.kubelet_service}}

- id: "8.4"
  name: Verify the kubelet service file ownership of root:root
  component: "kubelet"
  audit: stat -c %U:%G {{.kubelet_service}}

- id: "8.5"
  name: Verify the OpenShift default permissions for the proxy kubeconfig file
  component: "kubelet"
  audit: stat -c %a /etc/origin/node/node.kubeconfig

- id: "8.6"
  name: Verify the proxy kubeconfig file ownership of root:root
  component: "kubelet"
  audit: stat -c %U:%G /etc/origin/node/node.kubeconfig

- id: "8.7"
  name: Verify the OpenShift default permissions for the certificate authorities file.
  component: "kubelet"
  audit: stat -c %a /etc/origin/node/client-ca.crt

- id: "8.8"
  name: Verify the client certificate authorities file ownership of root:root
  component: "kubelet"
  audit: stat -c %U:%G /etc/origin/node/client-ca.crt